# Generated by Django 3.2 on 2021-10-23 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_registrarion_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='diatery_info',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='registration',
            name='medical_info',
            field=models.CharField(max_length=255),
        ),
    ]
