# Generated by Django 3.2 on 2021-10-23 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20211023_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='diatery_info',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='registration',
            name='medical_info',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
