# Generated by Django 3.2 on 2021-10-23 05:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20211023_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 23, 5, 47, 48, 457752, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
