# Generated by Django 3.2 on 2021-10-23 05:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 10, 23, 5, 48, 49, 927185, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
