# Generated by Django 3.2 on 2021-10-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='departure',
            field=models.CharField(default='Megatong Primary School', max_length=255),
            preserve_default=False,
        ),
    ]
